// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: issue/v1/issue.proto

package issuev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomNumber    string                 `protobuf:"bytes,1,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PhotoUrls     []string               `protobuf:"bytes,4,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueRequest) Reset() {
	*x = CreateIssueRequest{}
	mi := &file_issue_v1_issue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueRequest) ProtoMessage() {}

func (x *CreateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_issue_v1_issue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueRequest.ProtoReflect.Descriptor instead.
func (*CreateIssueRequest) Descriptor() ([]byte, []int) {
	return file_issue_v1_issue_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIssueRequest) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *CreateIssueRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateIssueRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIssueRequest) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

type CreateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueResponse) Reset() {
	*x = CreateIssueResponse{}
	mi := &file_issue_v1_issue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueResponse) ProtoMessage() {}

func (x *CreateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_issue_v1_issue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueResponse.ProtoReflect.Descriptor instead.
func (*CreateIssueResponse) Descriptor() ([]byte, []int) {
	return file_issue_v1_issue_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIssueResponse) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type GetIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueRequest) Reset() {
	*x = GetIssueRequest{}
	mi := &file_issue_v1_issue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueRequest) ProtoMessage() {}

func (x *GetIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_issue_v1_issue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueRequest.ProtoReflect.Descriptor instead.
func (*GetIssueRequest) Descriptor() ([]byte, []int) {
	return file_issue_v1_issue_proto_rawDescGZIP(), []int{2}
}

func (x *GetIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type GetIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,2,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueResponse) Reset() {
	*x = GetIssueResponse{}
	mi := &file_issue_v1_issue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueResponse) ProtoMessage() {}

func (x *GetIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_issue_v1_issue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueResponse.ProtoReflect.Descriptor instead.
func (*GetIssueResponse) Descriptor() ([]byte, []int) {
	return file_issue_v1_issue_proto_rawDescGZIP(), []int{3}
}

func (x *GetIssueResponse) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *GetIssueResponse) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *GetIssueResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetIssueResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetIssueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetIssueResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListIssuesByRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomNumber    string                 `protobuf:"bytes,1,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssuesByRoomRequest) Reset() {
	*x = ListIssuesByRoomRequest{}
	mi := &file_issue_v1_issue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssuesByRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssuesByRoomRequest) ProtoMessage() {}

func (x *ListIssuesByRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_issue_v1_issue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssuesByRoomRequest.ProtoReflect.Descriptor instead.
func (*ListIssuesByRoomRequest) Descriptor() ([]byte, []int) {
	return file_issue_v1_issue_proto_rawDescGZIP(), []int{4}
}

func (x *ListIssuesByRoomRequest) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

type ListIssuesByRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*GetIssueResponse    `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssuesByRoomResponse) Reset() {
	*x = ListIssuesByRoomResponse{}
	mi := &file_issue_v1_issue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssuesByRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssuesByRoomResponse) ProtoMessage() {}

func (x *ListIssuesByRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_issue_v1_issue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssuesByRoomResponse.ProtoReflect.Descriptor instead.
func (*ListIssuesByRoomResponse) Descriptor() ([]byte, []int) {
	return file_issue_v1_issue_proto_rawDescGZIP(), []int{5}
}

func (x *ListIssuesByRoomResponse) GetIssues() []*GetIssueResponse {
	if x != nil {
		return x.Issues
	}
	return nil
}

type UpdateIssueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	NewStatus     string                 `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueStatusRequest) Reset() {
	*x = UpdateIssueStatusRequest{}
	mi := &file_issue_v1_issue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueStatusRequest) ProtoMessage() {}

func (x *UpdateIssueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_issue_v1_issue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateIssueStatusRequest) Descriptor() ([]byte, []int) {
	return file_issue_v1_issue_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateIssueStatusRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *UpdateIssueStatusRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

type UpdateIssueStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueStatusResponse) Reset() {
	*x = UpdateIssueStatusResponse{}
	mi := &file_issue_v1_issue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueStatusResponse) ProtoMessage() {}

func (x *UpdateIssueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_issue_v1_issue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateIssueStatusResponse) Descriptor() ([]byte, []int) {
	return file_issue_v1_issue_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateIssueStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_issue_v1_issue_proto protoreflect.FileDescriptor

const file_issue_v1_issue_proto_rawDesc = "" +
	"\n" +
	"\x14issue/v1/issue.proto\x12\bissue.v1\"\x92\x01\n" +
	"\x12CreateIssueRequest\x12\x1f\n" +
	"\vroom_number\x18\x01 \x01(\tR\n" +
	"roomNumber\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\x04 \x03(\tR\tphotoUrls\"0\n" +
	"\x13CreateIssueResponse\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\",\n" +
	"\x0fGetIssueRequest\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\"\xc3\x01\n" +
	"\x10GetIssueResponse\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x1f\n" +
	"\vroom_number\x18\x02 \x01(\tR\n" +
	"roomNumber\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\":\n" +
	"\x17ListIssuesByRoomRequest\x12\x1f\n" +
	"\vroom_number\x18\x01 \x01(\tR\n" +
	"roomNumber\"N\n" +
	"\x18ListIssuesByRoomResponse\x122\n" +
	"\x06issues\x18\x01 \x03(\v2\x1a.issue.v1.GetIssueResponseR\x06issues\"T\n" +
	"\x18UpdateIssueStatusRequest\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x1d\n" +
	"\n" +
	"new_status\x18\x02 \x01(\tR\tnewStatus\"5\n" +
	"\x19UpdateIssueStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd6\x02\n" +
	"\fIssueService\x12J\n" +
	"\vCreateIssue\x12\x1c.issue.v1.CreateIssueRequest\x1a\x1d.issue.v1.CreateIssueResponse\x12A\n" +
	"\bGetIssue\x12\x19.issue.v1.GetIssueRequest\x1a\x1a.issue.v1.GetIssueResponse\x12Y\n" +
	"\x10ListIssuesByRoom\x12!.issue.v1.ListIssuesByRoomRequest\x1a\".issue.v1.ListIssuesByRoomResponse\x12\\\n" +
	"\x11UpdateIssueStatus\x12\".issue.v1.UpdateIssueStatusRequest\x1a#.issue.v1.UpdateIssueStatusResponseB5Z3github.com/Garryflop/DormOS-gen-go/issue/v1;issuev1b\x06proto3"

var (
	file_issue_v1_issue_proto_rawDescOnce sync.Once
	file_issue_v1_issue_proto_rawDescData []byte
)

func file_issue_v1_issue_proto_rawDescGZIP() []byte {
	file_issue_v1_issue_proto_rawDescOnce.Do(func() {
		file_issue_v1_issue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_issue_v1_issue_proto_rawDesc), len(file_issue_v1_issue_proto_rawDesc)))
	})
	return file_issue_v1_issue_proto_rawDescData
}

var file_issue_v1_issue_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_issue_v1_issue_proto_goTypes = []any{
	(*CreateIssueRequest)(nil),        // 0: issue.v1.CreateIssueRequest
	(*CreateIssueResponse)(nil),       // 1: issue.v1.CreateIssueResponse
	(*GetIssueRequest)(nil),           // 2: issue.v1.GetIssueRequest
	(*GetIssueResponse)(nil),          // 3: issue.v1.GetIssueResponse
	(*ListIssuesByRoomRequest)(nil),   // 4: issue.v1.ListIssuesByRoomRequest
	(*ListIssuesByRoomResponse)(nil),  // 5: issue.v1.ListIssuesByRoomResponse
	(*UpdateIssueStatusRequest)(nil),  // 6: issue.v1.UpdateIssueStatusRequest
	(*UpdateIssueStatusResponse)(nil), // 7: issue.v1.UpdateIssueStatusResponse
}
var file_issue_v1_issue_proto_depIdxs = []int32{
	3, // 0: issue.v1.ListIssuesByRoomResponse.issues:type_name -> issue.v1.GetIssueResponse
	0, // 1: issue.v1.IssueService.CreateIssue:input_type -> issue.v1.CreateIssueRequest
	2, // 2: issue.v1.IssueService.GetIssue:input_type -> issue.v1.GetIssueRequest
	4, // 3: issue.v1.IssueService.ListIssuesByRoom:input_type -> issue.v1.ListIssuesByRoomRequest
	6, // 4: issue.v1.IssueService.UpdateIssueStatus:input_type -> issue.v1.UpdateIssueStatusRequest
	1, // 5: issue.v1.IssueService.CreateIssue:output_type -> issue.v1.CreateIssueResponse
	3, // 6: issue.v1.IssueService.GetIssue:output_type -> issue.v1.GetIssueResponse
	5, // 7: issue.v1.IssueService.ListIssuesByRoom:output_type -> issue.v1.ListIssuesByRoomResponse
	7, // 8: issue.v1.IssueService.UpdateIssueStatus:output_type -> issue.v1.UpdateIssueStatusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_issue_v1_issue_proto_init() }
func file_issue_v1_issue_proto_init() {
	if File_issue_v1_issue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_issue_v1_issue_proto_rawDesc), len(file_issue_v1_issue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_issue_v1_issue_proto_goTypes,
		DependencyIndexes: file_issue_v1_issue_proto_depIdxs,
		MessageInfos:      file_issue_v1_issue_proto_msgTypes,
	}.Build()
	File_issue_v1_issue_proto = out.File
	file_issue_v1_issue_proto_goTypes = nil
	file_issue_v1_issue_proto_depIdxs = nil
}
