// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: activity/v1/activity.proto

package activityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- CreateEvent ---
type CreateEventRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Location        string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	StartTime       int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,6,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateEventRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateEventRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CreateEventRequest) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// --- GetEvent ---
type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetEventResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location        string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	StartTime       int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,7,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	RegisteredCount int32                  `protobuf:"varint,8,opt,name=registered_count,json=registeredCount,proto3" json:"registered_count,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetEventResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetEventResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetEventResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetEventResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetEventResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetEventResponse) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *GetEventResponse) GetRegisteredCount() int32 {
	if x != nil {
		return x.RegisteredCount
	}
	return 0
}

func (x *GetEventResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// --- ListEvents ---
type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpcomingOnly  bool                   `protobuf:"varint,1,opt,name=upcoming_only,json=upcomingOnly,proto3" json:"upcoming_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsRequest) GetUpcomingOnly() bool {
	if x != nil {
		return x.UpcomingOnly
	}
	return false
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*GetEventResponse    `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{5}
}

func (x *ListEventsResponse) GetEvents() []*GetEventResponse {
	if x != nil {
		return x.Events
	}
	return nil
}

// --- UpdateEvent ---
type UpdateEventRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location        string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	StartTime       int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,7,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateEventRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UpdateEventRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *UpdateEventRequest) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- DeleteEvent ---
type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- RegisterForEvent ---
type RegisterForEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterForEventRequest) Reset() {
	*x = RegisterForEventRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterForEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterForEventRequest) ProtoMessage() {}

func (x *RegisterForEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterForEventRequest.ProtoReflect.Descriptor instead.
func (*RegisterForEventRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterForEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RegisterForEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RegisterForEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterForEventResponse) Reset() {
	*x = RegisterForEventResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterForEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterForEventResponse) ProtoMessage() {}

func (x *RegisterForEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterForEventResponse.ProtoReflect.Descriptor instead.
func (*RegisterForEventResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterForEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- CancelRegistration ---
type CancelRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRegistrationRequest) Reset() {
	*x = CancelRegistrationRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRegistrationRequest) ProtoMessage() {}

func (x *CancelRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRegistrationRequest.ProtoReflect.Descriptor instead.
func (*CancelRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{12}
}

func (x *CancelRegistrationRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CancelRegistrationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRegistrationResponse) Reset() {
	*x = CancelRegistrationResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRegistrationResponse) ProtoMessage() {}

func (x *CancelRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRegistrationResponse.ProtoReflect.Descriptor instead.
func (*CancelRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{13}
}

func (x *CancelRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- RecordAttendance ---
type RecordAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Attended      bool                   `protobuf:"varint,3,opt,name=attended,proto3" json:"attended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAttendanceRequest) Reset() {
	*x = RecordAttendanceRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAttendanceRequest) ProtoMessage() {}

func (x *RecordAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAttendanceRequest.ProtoReflect.Descriptor instead.
func (*RecordAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{14}
}

func (x *RecordAttendanceRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RecordAttendanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecordAttendanceRequest) GetAttended() bool {
	if x != nil {
		return x.Attended
	}
	return false
}

type RecordAttendanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAttendanceResponse) Reset() {
	*x = RecordAttendanceResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAttendanceResponse) ProtoMessage() {}

func (x *RecordAttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAttendanceResponse.ProtoReflect.Descriptor instead.
func (*RecordAttendanceResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{15}
}

func (x *RecordAttendanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- SendNotification ---
type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"` // "EMAIL", "IN_APP", "BOTH"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{16}
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendNotificationRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{17}
}

func (x *SendNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- ListMyNotifications ---
type ListMyNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyNotificationsRequest) Reset() {
	*x = ListMyNotificationsRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyNotificationsRequest) ProtoMessage() {}

func (x *ListMyNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListMyNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{18}
}

func (x *ListMyNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListMyNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*NotificationItem    `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyNotificationsResponse) Reset() {
	*x = ListMyNotificationsResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyNotificationsResponse) ProtoMessage() {}

func (x *ListMyNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListMyNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{19}
}

func (x *ListMyNotificationsResponse) GetNotifications() []*NotificationItem {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type NotificationItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	IsRead         bool                   `protobuf:"varint,4,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationItem) Reset() {
	*x = NotificationItem{}
	mi := &file_activity_v1_activity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationItem) ProtoMessage() {}

func (x *NotificationItem) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationItem.ProtoReflect.Descriptor instead.
func (*NotificationItem) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{20}
}

func (x *NotificationItem) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationItem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *NotificationItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// --- MarkAsRead ---
type MarkAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{21}
}

func (x *MarkAsReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type MarkAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadResponse) Reset() {
	*x = MarkAsReadResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadResponse) ProtoMessage() {}

func (x *MarkAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAsReadResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{22}
}

func (x *MarkAsReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- MarkAllAsRead ---
type MarkAllAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadRequest) Reset() {
	*x = MarkAllAsReadRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadRequest) ProtoMessage() {}

func (x *MarkAllAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{23}
}

func (x *MarkAllAsReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MarkAllAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadResponse) Reset() {
	*x = MarkAllAsReadResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadResponse) ProtoMessage() {}

func (x *MarkAllAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{24}
}

func (x *MarkAllAsReadResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

var File_activity_v1_activity_proto protoreflect.FileDescriptor

const file_activity_v1_activity_proto_rawDesc = "" +
	"\n" +
	"\x1aactivity/v1/activity.proto\x12\vactivity.v1\"\xcd\x01\n" +
	"\x12CreateEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12)\n" +
	"\x10max_participants\x18\x06 \x01(\x05R\x0fmaxParticipants\"0\n" +
	"\x13CreateEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\",\n" +
	"\x0fGetEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\xb0\x02\n" +
	"\x10GetEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12)\n" +
	"\x10max_participants\x18\a \x01(\x05R\x0fmaxParticipants\x12)\n" +
	"\x10registered_count\x18\b \x01(\x05R\x0fregisteredCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"8\n" +
	"\x11ListEventsRequest\x12#\n" +
	"\rupcoming_only\x18\x01 \x01(\bR\fupcomingOnly\"K\n" +
	"\x12ListEventsResponse\x125\n" +
	"\x06events\x18\x01 \x03(\v2\x1d.activity.v1.GetEventResponseR\x06events\"\xe8\x01\n" +
	"\x12UpdateEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12)\n" +
	"\x10max_participants\x18\a \x01(\x05R\x0fmaxParticipants\"/\n" +
	"\x13UpdateEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x12DeleteEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"/\n" +
	"\x13DeleteEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x17RegisterForEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"4\n" +
	"\x18RegisterForEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"O\n" +
	"\x19CancelRegistrationRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"6\n" +
	"\x1aCancelRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"i\n" +
	"\x17RecordAttendanceRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\battended\x18\x03 \x01(\bR\battended\"4\n" +
	"\x18RecordAttendanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"|\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\"4\n" +
	"\x18SendNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x1aListMyNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"b\n" +
	"\x1bListMyNotificationsResponse\x12C\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1d.activity.v1.NotificationItemR\rnotifications\"\xa3\x01\n" +
	"\x10NotificationItem\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x17\n" +
	"\ais_read\x18\x04 \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"<\n" +
	"\x11MarkAsReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\".\n" +
	"\x12MarkAsReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x14MarkAllAsReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"<\n" +
	"\x15MarkAllAsReadResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount2\xba\b\n" +
	"\x0fActivityService\x12P\n" +
	"\vCreateEvent\x12\x1f.activity.v1.CreateEventRequest\x1a .activity.v1.CreateEventResponse\x12G\n" +
	"\bGetEvent\x12\x1c.activity.v1.GetEventRequest\x1a\x1d.activity.v1.GetEventResponse\x12M\n" +
	"\n" +
	"ListEvents\x12\x1e.activity.v1.ListEventsRequest\x1a\x1f.activity.v1.ListEventsResponse\x12P\n" +
	"\vUpdateEvent\x12\x1f.activity.v1.UpdateEventRequest\x1a .activity.v1.UpdateEventResponse\x12P\n" +
	"\vDeleteEvent\x12\x1f.activity.v1.DeleteEventRequest\x1a .activity.v1.DeleteEventResponse\x12_\n" +
	"\x10RegisterForEvent\x12$.activity.v1.RegisterForEventRequest\x1a%.activity.v1.RegisterForEventResponse\x12e\n" +
	"\x12CancelRegistration\x12&.activity.v1.CancelRegistrationRequest\x1a'.activity.v1.CancelRegistrationResponse\x12_\n" +
	"\x10RecordAttendance\x12$.activity.v1.RecordAttendanceRequest\x1a%.activity.v1.RecordAttendanceResponse\x12_\n" +
	"\x10SendNotification\x12$.activity.v1.SendNotificationRequest\x1a%.activity.v1.SendNotificationResponse\x12h\n" +
	"\x13ListMyNotifications\x12'.activity.v1.ListMyNotificationsRequest\x1a(.activity.v1.ListMyNotificationsResponse\x12M\n" +
	"\n" +
	"MarkAsRead\x12\x1e.activity.v1.MarkAsReadRequest\x1a\x1f.activity.v1.MarkAsReadResponse\x12V\n" +
	"\rMarkAllAsRead\x12!.activity.v1.MarkAllAsReadRequest\x1a\".activity.v1.MarkAllAsReadResponseB;Z9github.com/Garryflop/DormOS-gen-go/activity/v1;activityv1b\x06proto3"

var (
	file_activity_v1_activity_proto_rawDescOnce sync.Once
	file_activity_v1_activity_proto_rawDescData []byte
)

func file_activity_v1_activity_proto_rawDescGZIP() []byte {
	file_activity_v1_activity_proto_rawDescOnce.Do(func() {
		file_activity_v1_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_v1_activity_proto_rawDesc), len(file_activity_v1_activity_proto_rawDesc)))
	})
	return file_activity_v1_activity_proto_rawDescData
}

var file_activity_v1_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_activity_v1_activity_proto_goTypes = []any{
	(*CreateEventRequest)(nil),          // 0: activity.v1.CreateEventRequest
	(*CreateEventResponse)(nil),         // 1: activity.v1.CreateEventResponse
	(*GetEventRequest)(nil),             // 2: activity.v1.GetEventRequest
	(*GetEventResponse)(nil),            // 3: activity.v1.GetEventResponse
	(*ListEventsRequest)(nil),           // 4: activity.v1.ListEventsRequest
	(*ListEventsResponse)(nil),          // 5: activity.v1.ListEventsResponse
	(*UpdateEventRequest)(nil),          // 6: activity.v1.UpdateEventRequest
	(*UpdateEventResponse)(nil),         // 7: activity.v1.UpdateEventResponse
	(*DeleteEventRequest)(nil),          // 8: activity.v1.DeleteEventRequest
	(*DeleteEventResponse)(nil),         // 9: activity.v1.DeleteEventResponse
	(*RegisterForEventRequest)(nil),     // 10: activity.v1.RegisterForEventRequest
	(*RegisterForEventResponse)(nil),    // 11: activity.v1.RegisterForEventResponse
	(*CancelRegistrationRequest)(nil),   // 12: activity.v1.CancelRegistrationRequest
	(*CancelRegistrationResponse)(nil),  // 13: activity.v1.CancelRegistrationResponse
	(*RecordAttendanceRequest)(nil),     // 14: activity.v1.RecordAttendanceRequest
	(*RecordAttendanceResponse)(nil),    // 15: activity.v1.RecordAttendanceResponse
	(*SendNotificationRequest)(nil),     // 16: activity.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil),    // 17: activity.v1.SendNotificationResponse
	(*ListMyNotificationsRequest)(nil),  // 18: activity.v1.ListMyNotificationsRequest
	(*ListMyNotificationsResponse)(nil), // 19: activity.v1.ListMyNotificationsResponse
	(*NotificationItem)(nil),            // 20: activity.v1.NotificationItem
	(*MarkAsReadRequest)(nil),           // 21: activity.v1.MarkAsReadRequest
	(*MarkAsReadResponse)(nil),          // 22: activity.v1.MarkAsReadResponse
	(*MarkAllAsReadRequest)(nil),        // 23: activity.v1.MarkAllAsReadRequest
	(*MarkAllAsReadResponse)(nil),       // 24: activity.v1.MarkAllAsReadResponse
}
var file_activity_v1_activity_proto_depIdxs = []int32{
	3,  // 0: activity.v1.ListEventsResponse.events:type_name -> activity.v1.GetEventResponse
	20, // 1: activity.v1.ListMyNotificationsResponse.notifications:type_name -> activity.v1.NotificationItem
	0,  // 2: activity.v1.ActivityService.CreateEvent:input_type -> activity.v1.CreateEventRequest
	2,  // 3: activity.v1.ActivityService.GetEvent:input_type -> activity.v1.GetEventRequest
	4,  // 4: activity.v1.ActivityService.ListEvents:input_type -> activity.v1.ListEventsRequest
	6,  // 5: activity.v1.ActivityService.UpdateEvent:input_type -> activity.v1.UpdateEventRequest
	8,  // 6: activity.v1.ActivityService.DeleteEvent:input_type -> activity.v1.DeleteEventRequest
	10, // 7: activity.v1.ActivityService.RegisterForEvent:input_type -> activity.v1.RegisterForEventRequest
	12, // 8: activity.v1.ActivityService.CancelRegistration:input_type -> activity.v1.CancelRegistrationRequest
	14, // 9: activity.v1.ActivityService.RecordAttendance:input_type -> activity.v1.RecordAttendanceRequest
	16, // 10: activity.v1.ActivityService.SendNotification:input_type -> activity.v1.SendNotificationRequest
	18, // 11: activity.v1.ActivityService.ListMyNotifications:input_type -> activity.v1.ListMyNotificationsRequest
	21, // 12: activity.v1.ActivityService.MarkAsRead:input_type -> activity.v1.MarkAsReadRequest
	23, // 13: activity.v1.ActivityService.MarkAllAsRead:input_type -> activity.v1.MarkAllAsReadRequest
	1,  // 14: activity.v1.ActivityService.CreateEvent:output_type -> activity.v1.CreateEventResponse
	3,  // 15: activity.v1.ActivityService.GetEvent:output_type -> activity.v1.GetEventResponse
	5,  // 16: activity.v1.ActivityService.ListEvents:output_type -> activity.v1.ListEventsResponse
	7,  // 17: activity.v1.ActivityService.UpdateEvent:output_type -> activity.v1.UpdateEventResponse
	9,  // 18: activity.v1.ActivityService.DeleteEvent:output_type -> activity.v1.DeleteEventResponse
	11, // 19: activity.v1.ActivityService.RegisterForEvent:output_type -> activity.v1.RegisterForEventResponse
	13, // 20: activity.v1.ActivityService.CancelRegistration:output_type -> activity.v1.CancelRegistrationResponse
	15, // 21: activity.v1.ActivityService.RecordAttendance:output_type -> activity.v1.RecordAttendanceResponse
	17, // 22: activity.v1.ActivityService.SendNotification:output_type -> activity.v1.SendNotificationResponse
	19, // 23: activity.v1.ActivityService.ListMyNotifications:output_type -> activity.v1.ListMyNotificationsResponse
	22, // 24: activity.v1.ActivityService.MarkAsRead:output_type -> activity.v1.MarkAsReadResponse
	24, // 25: activity.v1.ActivityService.MarkAllAsRead:output_type -> activity.v1.MarkAllAsReadResponse
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_activity_v1_activity_proto_init() }
func file_activity_v1_activity_proto_init() {
	if File_activity_v1_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_v1_activity_proto_rawDesc), len(file_activity_v1_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_activity_v1_activity_proto_goTypes,
		DependencyIndexes: file_activity_v1_activity_proto_depIdxs,
		MessageInfos:      file_activity_v1_activity_proto_msgTypes,
	}.Build()
	File_activity_v1_activity_proto = out.File
	file_activity_v1_activity_proto_goTypes = nil
	file_activity_v1_activity_proto_depIdxs = nil
}
