// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: room/v1/room.proto

package roomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- CreateRoom ---
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomNumber    string                 `protobuf:"bytes,1,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Floor         int32                  `protobuf:"varint,2,opt,name=floor,proto3" json:"floor,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *CreateRoomRequest) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *CreateRoomRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_room_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// --- GetRoom ---
type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,2,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Floor         int32                  `protobuf:"varint,3,opt,name=floor,proto3" json:"floor,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Occupied      int32                  `protobuf:"varint,5,opt,name=occupied,proto3" json:"occupied,omitempty"`
	Residents     []*ResidentInfo        `protobuf:"bytes,6,rep,name=residents,proto3" json:"residents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_room_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomResponse) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *GetRoomResponse) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *GetRoomResponse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *GetRoomResponse) GetOccupied() int32 {
	if x != nil {
		return x.Occupied
	}
	return 0
}

func (x *GetRoomResponse) GetResidents() []*ResidentInfo {
	if x != nil {
		return x.Residents
	}
	return nil
}

// --- ListRooms ---
type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Floor         int32                  `protobuf:"varint,1,opt,name=floor,proto3" json:"floor,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_room_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoomsRequest) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*GetRoomResponse     `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_room_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *ListRoomsResponse) GetRooms() []*GetRoomResponse {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// --- AssignResident ---
type AssignResidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignResidentRequest) Reset() {
	*x = AssignResidentRequest{}
	mi := &file_room_v1_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignResidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignResidentRequest) ProtoMessage() {}

func (x *AssignResidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignResidentRequest.ProtoReflect.Descriptor instead.
func (*AssignResidentRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *AssignResidentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignResidentRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type AssignResidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResidentId    string                 `protobuf:"bytes,1,opt,name=resident_id,json=residentId,proto3" json:"resident_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignResidentResponse) Reset() {
	*x = AssignResidentResponse{}
	mi := &file_room_v1_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignResidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignResidentResponse) ProtoMessage() {}

func (x *AssignResidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignResidentResponse.ProtoReflect.Descriptor instead.
func (*AssignResidentResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{7}
}

func (x *AssignResidentResponse) GetResidentId() string {
	if x != nil {
		return x.ResidentId
	}
	return ""
}

// --- RemoveResident ---
type RemoveResidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResidentRequest) Reset() {
	*x = RemoveResidentRequest{}
	mi := &file_room_v1_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResidentRequest) ProtoMessage() {}

func (x *RemoveResidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResidentRequest.ProtoReflect.Descriptor instead.
func (*RemoveResidentRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveResidentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveResidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResidentResponse) Reset() {
	*x = RemoveResidentResponse{}
	mi := &file_room_v1_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResidentResponse) ProtoMessage() {}

func (x *RemoveResidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResidentResponse.ProtoReflect.Descriptor instead.
func (*RemoveResidentResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveResidentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- GetResident ---
type GetResidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResidentRequest) Reset() {
	*x = GetResidentRequest{}
	mi := &file_room_v1_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResidentRequest) ProtoMessage() {}

func (x *GetResidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResidentRequest.ProtoReflect.Descriptor instead.
func (*GetResidentRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{10}
}

func (x *GetResidentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetResidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResidentId    string                 `protobuf:"bytes,1,opt,name=resident_id,json=residentId,proto3" json:"resident_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,3,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	CheckInDate   int64                  `protobuf:"varint,5,opt,name=check_in_date,json=checkInDate,proto3" json:"check_in_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResidentResponse) Reset() {
	*x = GetResidentResponse{}
	mi := &file_room_v1_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResidentResponse) ProtoMessage() {}

func (x *GetResidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResidentResponse.ProtoReflect.Descriptor instead.
func (*GetResidentResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{11}
}

func (x *GetResidentResponse) GetResidentId() string {
	if x != nil {
		return x.ResidentId
	}
	return ""
}

func (x *GetResidentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetResidentResponse) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *GetResidentResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetResidentResponse) GetCheckInDate() int64 {
	if x != nil {
		return x.CheckInDate
	}
	return 0
}

// --- ListResidents ---
type ListResidentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // optional filter
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                   // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResidentsRequest) Reset() {
	*x = ListResidentsRequest{}
	mi := &file_room_v1_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResidentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResidentsRequest) ProtoMessage() {}

func (x *ListResidentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResidentsRequest.ProtoReflect.Descriptor instead.
func (*ListResidentsRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{12}
}

func (x *ListResidentsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ListResidentsRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ListResidentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Residents     []*GetResidentResponse `protobuf:"bytes,1,rep,name=residents,proto3" json:"residents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResidentsResponse) Reset() {
	*x = ListResidentsResponse{}
	mi := &file_room_v1_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResidentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResidentsResponse) ProtoMessage() {}

func (x *ListResidentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResidentsResponse.ProtoReflect.Descriptor instead.
func (*ListResidentsResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{13}
}

func (x *ListResidentsResponse) GetResidents() []*GetResidentResponse {
	if x != nil {
		return x.Residents
	}
	return nil
}

func (x *ListResidentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- UpdateResidentRole ---
type UpdateResidentRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewRole       string                 `protobuf:"bytes,2,opt,name=new_role,json=newRole,proto3" json:"new_role,omitempty"` // "student", "manager", "admin"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResidentRoleRequest) Reset() {
	*x = UpdateResidentRoleRequest{}
	mi := &file_room_v1_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResidentRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResidentRoleRequest) ProtoMessage() {}

func (x *UpdateResidentRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResidentRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateResidentRoleRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateResidentRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateResidentRoleRequest) GetNewRole() string {
	if x != nil {
		return x.NewRole
	}
	return ""
}

type UpdateResidentRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResidentRoleResponse) Reset() {
	*x = UpdateResidentRoleResponse{}
	mi := &file_room_v1_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResidentRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResidentRoleResponse) ProtoMessage() {}

func (x *UpdateResidentRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResidentRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateResidentRoleResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateResidentRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- GetDashboardStats ---
type GetDashboardStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardStatsRequest) Reset() {
	*x = GetDashboardStatsRequest{}
	mi := &file_room_v1_room_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardStatsRequest) ProtoMessage() {}

func (x *GetDashboardStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardStatsRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{16}
}

type GetDashboardStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalResidents int32                  `protobuf:"varint,1,opt,name=total_residents,json=totalResidents,proto3" json:"total_residents,omitempty"`
	TotalRooms     int32                  `protobuf:"varint,2,opt,name=total_rooms,json=totalRooms,proto3" json:"total_rooms,omitempty"`
	OccupiedRooms  int32                  `protobuf:"varint,3,opt,name=occupied_rooms,json=occupiedRooms,proto3" json:"occupied_rooms,omitempty"`
	AvailableBeds  int32                  `protobuf:"varint,4,opt,name=available_beds,json=availableBeds,proto3" json:"available_beds,omitempty"`
	OpenIssues     int32                  `protobuf:"varint,5,opt,name=open_issues,json=openIssues,proto3" json:"open_issues,omitempty"`
	UpcomingEvents int32                  `protobuf:"varint,6,opt,name=upcoming_events,json=upcomingEvents,proto3" json:"upcoming_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDashboardStatsResponse) Reset() {
	*x = GetDashboardStatsResponse{}
	mi := &file_room_v1_room_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardStatsResponse) ProtoMessage() {}

func (x *GetDashboardStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardStatsResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{17}
}

func (x *GetDashboardStatsResponse) GetTotalResidents() int32 {
	if x != nil {
		return x.TotalResidents
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetTotalRooms() int32 {
	if x != nil {
		return x.TotalRooms
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetOccupiedRooms() int32 {
	if x != nil {
		return x.OccupiedRooms
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetAvailableBeds() int32 {
	if x != nil {
		return x.AvailableBeds
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetOpenIssues() int32 {
	if x != nil {
		return x.OpenIssues
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetUpcomingEvents() int32 {
	if x != nil {
		return x.UpcomingEvents
	}
	return 0
}

// --- Shared ---
type ResidentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResidentInfo) Reset() {
	*x = ResidentInfo{}
	mi := &file_room_v1_room_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResidentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResidentInfo) ProtoMessage() {}

func (x *ResidentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResidentInfo.ProtoReflect.Descriptor instead.
func (*ResidentInfo) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{18}
}

func (x *ResidentInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResidentInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ResidentInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_room_v1_room_proto protoreflect.FileDescriptor

const file_room_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x12room/v1/room.proto\x12\aroom.v1\"f\n" +
	"\x11CreateRoomRequest\x12\x1f\n" +
	"\vroom_number\x18\x01 \x01(\tR\n" +
	"roomNumber\x12\x14\n" +
	"\x05floor\x18\x02 \x01(\x05R\x05floor\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\"-\n" +
	"\x12CreateRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\")\n" +
	"\x0eGetRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\xce\x01\n" +
	"\x0fGetRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vroom_number\x18\x02 \x01(\tR\n" +
	"roomNumber\x12\x14\n" +
	"\x05floor\x18\x03 \x01(\x05R\x05floor\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12\x1a\n" +
	"\boccupied\x18\x05 \x01(\x05R\boccupied\x123\n" +
	"\tresidents\x18\x06 \x03(\v2\x15.room.v1.ResidentInfoR\tresidents\"(\n" +
	"\x10ListRoomsRequest\x12\x14\n" +
	"\x05floor\x18\x01 \x01(\x05R\x05floor\"C\n" +
	"\x11ListRoomsResponse\x12.\n" +
	"\x05rooms\x18\x01 \x03(\v2\x18.room.v1.GetRoomResponseR\x05rooms\"I\n" +
	"\x15AssignResidentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"9\n" +
	"\x16AssignResidentResponse\x12\x1f\n" +
	"\vresident_id\x18\x01 \x01(\tR\n" +
	"residentId\"0\n" +
	"\x15RemoveResidentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"2\n" +
	"\x16RemoveResidentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x12GetResidentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xa8\x01\n" +
	"\x13GetResidentResponse\x12\x1f\n" +
	"\vresident_id\x18\x01 \x01(\tR\n" +
	"residentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vroom_number\x18\x03 \x01(\tR\n" +
	"roomNumber\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\"\n" +
	"\rcheck_in_date\x18\x05 \x01(\x03R\vcheckInDate\"C\n" +
	"\x14ListResidentsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"i\n" +
	"\x15ListResidentsResponse\x12:\n" +
	"\tresidents\x18\x01 \x03(\v2\x1c.room.v1.GetResidentResponseR\tresidents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"O\n" +
	"\x19UpdateResidentRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bnew_role\x18\x02 \x01(\tR\anewRole\"6\n" +
	"\x1aUpdateResidentRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1a\n" +
	"\x18GetDashboardStatsRequest\"\xfd\x01\n" +
	"\x19GetDashboardStatsResponse\x12'\n" +
	"\x0ftotal_residents\x18\x01 \x01(\x05R\x0etotalResidents\x12\x1f\n" +
	"\vtotal_rooms\x18\x02 \x01(\x05R\n" +
	"totalRooms\x12%\n" +
	"\x0eoccupied_rooms\x18\x03 \x01(\x05R\roccupiedRooms\x12%\n" +
	"\x0eavailable_beds\x18\x04 \x01(\x05R\ravailableBeds\x12\x1f\n" +
	"\vopen_issues\x18\x05 \x01(\x05R\n" +
	"openIssues\x12'\n" +
	"\x0fupcoming_events\x18\x06 \x01(\x05R\x0eupcomingEvents\"X\n" +
	"\fResidentInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role2\xd1\x05\n" +
	"\vRoomService\x12E\n" +
	"\n" +
	"CreateRoom\x12\x1a.room.v1.CreateRoomRequest\x1a\x1b.room.v1.CreateRoomResponse\x12<\n" +
	"\aGetRoom\x12\x17.room.v1.GetRoomRequest\x1a\x18.room.v1.GetRoomResponse\x12B\n" +
	"\tListRooms\x12\x19.room.v1.ListRoomsRequest\x1a\x1a.room.v1.ListRoomsResponse\x12Q\n" +
	"\x0eAssignResident\x12\x1e.room.v1.AssignResidentRequest\x1a\x1f.room.v1.AssignResidentResponse\x12Q\n" +
	"\x0eRemoveResident\x12\x1e.room.v1.RemoveResidentRequest\x1a\x1f.room.v1.RemoveResidentResponse\x12H\n" +
	"\vGetResident\x12\x1b.room.v1.GetResidentRequest\x1a\x1c.room.v1.GetResidentResponse\x12N\n" +
	"\rListResidents\x12\x1d.room.v1.ListResidentsRequest\x1a\x1e.room.v1.ListResidentsResponse\x12]\n" +
	"\x12UpdateResidentRole\x12\".room.v1.UpdateResidentRoleRequest\x1a#.room.v1.UpdateResidentRoleResponse\x12Z\n" +
	"\x11GetDashboardStats\x12!.room.v1.GetDashboardStatsRequest\x1a\".room.v1.GetDashboardStatsResponseB3Z1github.com/Garryflop/DormOS-gen-go/room/v1;roomv1b\x06proto3"

var (
	file_room_v1_room_proto_rawDescOnce sync.Once
	file_room_v1_room_proto_rawDescData []byte
)

func file_room_v1_room_proto_rawDescGZIP() []byte {
	file_room_v1_room_proto_rawDescOnce.Do(func() {
		file_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)))
	})
	return file_room_v1_room_proto_rawDescData
}

var file_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_room_v1_room_proto_goTypes = []any{
	(*CreateRoomRequest)(nil),          // 0: room.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),         // 1: room.v1.CreateRoomResponse
	(*GetRoomRequest)(nil),             // 2: room.v1.GetRoomRequest
	(*GetRoomResponse)(nil),            // 3: room.v1.GetRoomResponse
	(*ListRoomsRequest)(nil),           // 4: room.v1.ListRoomsRequest
	(*ListRoomsResponse)(nil),          // 5: room.v1.ListRoomsResponse
	(*AssignResidentRequest)(nil),      // 6: room.v1.AssignResidentRequest
	(*AssignResidentResponse)(nil),     // 7: room.v1.AssignResidentResponse
	(*RemoveResidentRequest)(nil),      // 8: room.v1.RemoveResidentRequest
	(*RemoveResidentResponse)(nil),     // 9: room.v1.RemoveResidentResponse
	(*GetResidentRequest)(nil),         // 10: room.v1.GetResidentRequest
	(*GetResidentResponse)(nil),        // 11: room.v1.GetResidentResponse
	(*ListResidentsRequest)(nil),       // 12: room.v1.ListResidentsRequest
	(*ListResidentsResponse)(nil),      // 13: room.v1.ListResidentsResponse
	(*UpdateResidentRoleRequest)(nil),  // 14: room.v1.UpdateResidentRoleRequest
	(*UpdateResidentRoleResponse)(nil), // 15: room.v1.UpdateResidentRoleResponse
	(*GetDashboardStatsRequest)(nil),   // 16: room.v1.GetDashboardStatsRequest
	(*GetDashboardStatsResponse)(nil),  // 17: room.v1.GetDashboardStatsResponse
	(*ResidentInfo)(nil),               // 18: room.v1.ResidentInfo
}
var file_room_v1_room_proto_depIdxs = []int32{
	18, // 0: room.v1.GetRoomResponse.residents:type_name -> room.v1.ResidentInfo
	3,  // 1: room.v1.ListRoomsResponse.rooms:type_name -> room.v1.GetRoomResponse
	11, // 2: room.v1.ListResidentsResponse.residents:type_name -> room.v1.GetResidentResponse
	0,  // 3: room.v1.RoomService.CreateRoom:input_type -> room.v1.CreateRoomRequest
	2,  // 4: room.v1.RoomService.GetRoom:input_type -> room.v1.GetRoomRequest
	4,  // 5: room.v1.RoomService.ListRooms:input_type -> room.v1.ListRoomsRequest
	6,  // 6: room.v1.RoomService.AssignResident:input_type -> room.v1.AssignResidentRequest
	8,  // 7: room.v1.RoomService.RemoveResident:input_type -> room.v1.RemoveResidentRequest
	10, // 8: room.v1.RoomService.GetResident:input_type -> room.v1.GetResidentRequest
	12, // 9: room.v1.RoomService.ListResidents:input_type -> room.v1.ListResidentsRequest
	14, // 10: room.v1.RoomService.UpdateResidentRole:input_type -> room.v1.UpdateResidentRoleRequest
	16, // 11: room.v1.RoomService.GetDashboardStats:input_type -> room.v1.GetDashboardStatsRequest
	1,  // 12: room.v1.RoomService.CreateRoom:output_type -> room.v1.CreateRoomResponse
	3,  // 13: room.v1.RoomService.GetRoom:output_type -> room.v1.GetRoomResponse
	5,  // 14: room.v1.RoomService.ListRooms:output_type -> room.v1.ListRoomsResponse
	7,  // 15: room.v1.RoomService.AssignResident:output_type -> room.v1.AssignResidentResponse
	9,  // 16: room.v1.RoomService.RemoveResident:output_type -> room.v1.RemoveResidentResponse
	11, // 17: room.v1.RoomService.GetResident:output_type -> room.v1.GetResidentResponse
	13, // 18: room.v1.RoomService.ListResidents:output_type -> room.v1.ListResidentsResponse
	15, // 19: room.v1.RoomService.UpdateResidentRole:output_type -> room.v1.UpdateResidentRoleResponse
	17, // 20: room.v1.RoomService.GetDashboardStats:output_type -> room.v1.GetDashboardStatsResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_room_v1_room_proto_init() }
func file_room_v1_room_proto_init() {
	if File_room_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_v1_room_proto_goTypes,
		DependencyIndexes: file_room_v1_room_proto_depIdxs,
		MessageInfos:      file_room_v1_room_proto_msgTypes,
	}.Build()
	File_room_v1_room_proto = out.File
	file_room_v1_room_proto_goTypes = nil
	file_room_v1_room_proto_depIdxs = nil
}
